export interface AssistanceForm {
   name: string,
   surname: string,
   patronymic: string,
   phone: string,
   birth: string,
   district: string,
   street: string,
   house: string,
   flat: string,
   people_num: number,
   people_fio?: Array<string>,
   invalids: string,
   children: string,
   children_age?: Array<string>,
   food: string,
   drugs: string,
   water: string,
   products_detail: string,
   gigien: string,
   gigien_num: string,
   pampers: string,
   diet: string,
   pers_data_agreement: boolean,
   photo_agreement: boolean,
}


